"""
Scratch-1: The Transformer Backbone
CSCI 7000 - VLA Foundations

Template for implementing a decoder-only Transformer from scratch.
Students must complete the TODO sections for:
1. CausalSelfAttention
2. RMSNorm
3. Training loop


Generated by ChatGPT based on the original VLA Foundations assignment.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import math
from typing import Optional, Tuple    

class RMSNorm(nn.Module):
    """
    Root Mean Square Layer Normalization

    Paper: https://arxiv.org/abs/1910.07467
    Used in: Llama-3, Grok, PaLM

    Formula:
        a_bar_i = (a_i / RMS(a)) * g_i
        where RMS(a) = sqrt(mean(a^2) + eps)
    """

    def __init__(self, dim: int, eps: float = 1e-6):
        super().__init__()
        self.eps = eps
        # TODO: Initialize learnable scale parameter 'g' (gamma)
        self.scale = nn.Parameter(torch.ones(dim))


    def get_rms(self, x: torch.Tensor) -> torch.Tensor:
        """Compute RMS of tensor x along the last dimension"""
        return torch.rsqrt(torch.mean(x.pow(2), dim=-1, keepdim=True) + self.eps)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Input tensor of shape (batch, seq_len, dim)
        Returns:
            Normalized tensor of same shape
        """
        # TODO: Implement RMSNorm
        # Step 1: Compute RMS (root mean square) along the last dimension
        # Step 2: Normalize by dividing x by RMS
        # Step 3: Apply learnable scale parameter

        # HINT: Use torch.mean, torch.rsqrt for efficiency
        # rms = torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)

        rms = self.get_rms(x)
        x_normalized = x * rms
        x_rms_normed = x_normalized * self.scale
        return x_rms_normed


class RotaryPositionalEmbedding(nn.Module):
    """
    Rotary Position Embedding (RoPE)

    Paper: RoFormer (Su et al., 2021) - https://arxiv.org/abs/2104.09864
    Used in: Llama-3, PaLM-E, GPT-NeoX

    Key Idea: Rotate pairs of dimensions by an angle proportional to position
    """

    def __init__(self, dim: int, max_seq_len: int = 2048, base: float = 10000.0):
        super().__init__()
        self.dim = dim #This is head_dim, not model dim.
        self.max_seq_len = max_seq_len
        self.base = base

        # Precompute rotation frequencies
        inv_freq = 1.0 / (base ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer("inv_freq", inv_freq)

        # Precompute cos and sin for all positions
        self._build_cache(max_seq_len)

    def _build_cache(self, seq_len: int):
        """Precompute cos and sin values for all positions"""
        t = torch.arange(seq_len, device=self.inv_freq.device).type_as(self.inv_freq)
        freqs = torch.einsum("i,j->ij", t, self.inv_freq)  # (seq_len, dim//2)
        emb = torch.cat([freqs, freqs], dim=-1)  # (seq_len, dim)
        self.register_buffer("cos_cached", emb.cos(), persistent=False)
        self.register_buffer("sin_cached", emb.sin(), persistent=False)

    def rotate_half(self, x: torch.Tensor) -> torch.Tensor:
        """Helper function to rotate tensor by swapping and negating half the dimensions"""
        x1, x2 = x.chunk(2, dim=-1)
        return torch.cat([-x2, x1], dim=-1)

    def forward(self, q: torch.Tensor, k: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Apply rotary embeddings to query and key tensors

        Args:
            q: Query tensor (batch, num_heads, seq_len, head_dim)
            k: Key tensor (batch, num_heads, seq_len, head_dim)
        Returns:
            Rotated (q, k) tensors
        """
        seq_len = q.shape[2]

        # Get cached cos/sin values
        cos = self.cos_cached[:seq_len, ...]
        sin = self.sin_cached[:seq_len, ...]

        # Apply rotation: q_rot = q * cos + rotate_half(q) * sin
        q_rot = (q * cos) + (self.rotate_half(q) * sin)
        k_rot = (k * cos) + (self.rotate_half(k) * sin)

        return q_rot, k_rot


class CausalSelfAttention(nn.Module):
    """
    Multi-Head Causal Self-Attention with RoPE

    Key constraints:
    - Token at position t can only attend to positions <= t
    - Uses RoPE instead of absolute positional embeddings
    """

    def __init__(self, dim: int, num_heads: int, dropout: float = 0.1):
        super().__init__()
        assert dim % num_heads == 0, "dim must be divisible by num_heads"

        self.dim = dim
        self.num_heads = num_heads
        self.head_dim = dim // num_heads
        self.scale = self.head_dim ** -0.5

        # Linear projections for Q, K, V
        self.qkv_proj = nn.Linear(dim, 3 * dim, bias=False)
        self.out_proj = nn.Linear(dim, dim, bias=False)

        # Dropout
        self.attn_dropout = nn.Dropout(dropout)
        self.resid_dropout = nn.Dropout(dropout)

        # Rotary embeddings
        self.rope = RotaryPositionalEmbedding(self.head_dim)

    def forward(self, x: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        Args:
            x: Input tensor (batch, seq_len, dim)
            mask: Optional attention mask (seq_len, seq_len)
        Returns:
            Output tensor (batch, seq_len, dim)
        """
        batch_size, seq_len, _ = x.shape


        # Step 1: Project input to Q, K, V
        qkv = self.qkv_proj(x)  # (batch, seq_len, 3*dim)
        # Split into Q, K, V and reshape for multi-head attention
        # Hint: Use .view() and .transpose() to get shape (batch, num_heads, seq_len, head_dim)
        q,k,v = qkv.chunk(3, dim=-1) #split into 3 equal chunks along the last dimension

        # q.shape -> (batch, seq_len, dim)
        # We need q's shape to be (batch, num_heads, seq_len, head_dim)
        q = q.view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        #Same for k and v
        k = k.view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        v = v.view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)


        # Step 2: Apply RoPE to Q and K
        q, k = self.rope(q, k) #Both q and k still have shape (batch, num_heads, seq_len, head_dim)

        # Step 3: Compute attention scores
        # scores = (Q @ K^T) / sqrt(d_k)
        # Hint: Use torch.matmul or @ operator
        # Shape should be (batch, num_heads, seq_len, seq_len)
        # q.shape = (batch, num_heads, seq_len, head_dim)
        # k.shape = (batch, num_heads, seq_len, head_dim)
        # k.transpose(2, 3).shape = (batch, num_heads, head_dim, seq_len)
        # To multiply last two dimensions of q and k across all batches
        # and heads, we use torch.matmul
        scores = torch.matmul(q, k.transpose(2,3)) * self.scale
        # Same as scores = (q @ k.transpose(-2, -1)) * self.scale
        #scores.shape = (batch, num_heads, seq_len, seq_len)


        # Step 4: Apply causal mask
        # The mask should prevent position i from attending to positions > i
        # Hint: Create a lower-triangular matrix using torch.tril
        if mask is None:
            mask = torch.tril(torch.ones((seq_len, seq_len), device=x.device))
        # causal_mask shape = (seq_len, seq_len)
        # causal_mask[i, j] = 1 if j <= i else 0
        # Set masked positions to -inf BEFORE softmax
        # Example: scores = scores.masked_fill(mask == 0, float('-inf'))
        scores = scores.masked_fill(mask==0, float('-inf')) 
        #masked_fill replaces elements where the mask is 0 with value -inf
        #scores.shape = (batch, num_heads, seq_len, seq_len)


        # Step 5: Apply softmax and dropout
        # attn_weights = F.softmax(scores, dim=-1)
        # attn_weights = self.attn_dropout(attn_weights)
        # Convert attention scores into attention weights using softmax
        attn_weights = F.softmax(scores, dim=-1) #Apply softmax along the last dimension (seq_len)
        # Same as saying attn_weights = torch.softmax(scores, dim=-1)
        # attn_weights.shape = (batch, num_heads, seq_len, seq_len)
        attn_weights = self.attn_dropout(attn_weights)
        # attn_weights.shape = (batch, num_heads, seq_len, seq_len)

        # Step 6: Apply attention to values
        # attn_weights.shape = (batch, num_heads, seq_len, seq_len)
        # v.shape = (batch, num_heads, seq_len, head_dim)
        out = attn_weights @ v
        # out.shape = (batch, num_heads, seq_len, head_dim)


        # Step 7: Reshape and project back
        # Concatenate heads and apply output projection
        # Hint: Use .transpose() and .contiguous().view() to reshape
        # out.shape = (batch, num_heads, seq_len, head_dim)
        # Desired output's shape is (batch, seq_len, dim)
        # out.transpose(1,2).shape = (batch, seq_len, num_heads, head_dim)
        out = out.transpose(1, 2).contiguous().view(batch_size, seq_len, self.dim)
        # Called contiguous because it physically rearranges data in memory
        # and makes the layout compatible with .view()
        # out.shape = (batch, seq_len, dim)
        out = self.out_proj(out)
        # Applies final linear projection to each token and mixes information across heads
        # out[b,t] = W_out @ out[b,t] for each batch b and token t
        out = self.resid_dropout(out)
        # Applies dropout to the attention output

        return out


class FeedForward(nn.Module):
    """
    Position-wise Feed-Forward Network with SwiGLU activation

    Used in modern LLMs for better performance than standard ReLU
    """

    def __init__(self, dim: int, hidden_dim: int, dropout: float = 0.1):
        super().__init__()
        self.fc1 = nn.Linear(dim, hidden_dim, bias=False)
        self.fc2 = nn.Linear(hidden_dim, dim, bias=False)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x: Input tensor (batch, seq_len, dim)
        Returns:
            Output tensor (batch, seq_len, dim)
        """
        x = self.fc1(x)
        x = F.silu(x)  # SwiGLU activation (SiLU = Swish)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.dropout(x)
        return x


class TransformerBlock(nn.Module):
    """
    A single Transformer decoder block

    Architecture:
        x = x + Attention(RMSNorm(x))
        x = x + FeedForward(RMSNorm(x))
    """

    def __init__(self, dim: int, num_heads: int, ff_hidden_dim: int, dropout: float = 0.1):
        super().__init__()
        self.attention = CausalSelfAttention(dim, num_heads, dropout)
        self.feed_forward = FeedForward(dim, ff_hidden_dim, dropout)
        self.norm1 = RMSNorm(dim)
        self.norm2 = RMSNorm(dim)

    def forward(self, x: torch.Tensor, mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        Args:
            x: Input tensor (batch, seq_len, dim)
            mask: Optional attention mask
        Returns:
            Output tensor (batch, seq_len, dim)
        """
        # Pre-norm architecture (norm before attention/FF)
        x = x + self.attention(self.norm1(x), mask)
        x = x + self.feed_forward(self.norm2(x))
        return x


class DecoderOnlyTransformer(nn.Module):
    """
    Decoder-only Transformer for next-token prediction on robot trajectories

    Architecture similar to GPT, but for robotic control sequences

    Decoder-only Transformer that predicts discrete actions conditioned on continuous states.

    Input:  states  (batch, seq_len, state_dim)   state_dim = 10 here
    Output: logits  (batch, seq_len, vocab_size)  vocab_size = 256 actions
    """

    def __init__(
        self,
        vocab_size: int, #number of discrete tokens (e.g., quantized actions/states)
        dim: int, #embedding dimension/size
        num_layers: int, #how many TransformerBlocks stacked
        num_heads: int, #number of attention heads in each block
        ff_hidden_dim: int, #hidden dimension size in feed-forward network
        max_seq_len: int = 2048, #maximum sequence length (context window)
        dropout: float = 0.1, #dropout rate
    ):
        super().__init__()
        self.vocab_size = vocab_size
        self.dim = dim
        self.max_seq_len = max_seq_len

        # Token embedding
        self.token_embedding = nn.Embedding(vocab_size, dim)
        # Maps integer tokens to embeddings of size dim
        # These embeddings are learned during training

        # Transformer blocks
        self.blocks = nn.ModuleList([
            TransformerBlock(dim, num_heads, ff_hidden_dim, dropout)
            for _ in range(num_layers)
        ])

        # Final norm and projection to vocabulary
        self.norm_final = RMSNorm(dim) #stabilizes the final representation before logits
        self.lm_head = nn.Linear(dim, vocab_size, bias=False)
        # converts each token vector into logits over next-token vocabulary
        # Each position output is the logits/scores value for the next token
        # So the overall output is the logits/scores value for each token position 
        # in the input sequence. Softmax can be applied to convert logits to probabilities. 

        # Initialize weights
        self.apply(self._init_weights)
        self.mask_future = True  # Always use causal mask

    def _init_weights(self, module):
        """Initialize weights following standard Transformer initialization"""
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(
        self,
        input_ids: torch.Tensor,
        targets: Optional[torch.Tensor] = None,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor]]:
        """
        Args:
            input_ids: Input token indices (batch, seq_len)
            targets: Target token indices for training (batch, seq_len)
        Returns:
            logits: Output logits (batch, seq_len, vocab_size)
            loss: Cross-entropy loss if targets provided, else None
        """
        batch_size, seq_len = input_ids.shape

        # Embed tokens
        x = self.token_embedding(input_ids)  # (batch, seq_len, dim)

        # Create causal mask (lower triangular)
        if self.mask_future:
            mask = torch.tril(torch.ones(seq_len, seq_len, device=x.device))
        else:
            mask = torch.ones(seq_len, seq_len, device=x.device)

        # Apply transformer blocks
        for block in self.blocks:
            x = block(x, mask)

        # Final norm and projection
        x = self.norm_final(x)
        logits = self.lm_head(x)  # (batch, seq_len, vocab_size)
        # logits[b, t, :] are the unnormalized scores for what token comes next after position t.

        # Compute loss if targets provided
        # Here we compute the next token prediction loss.
        # The model is trained to answer: 
        # "Given tokens up to time t, what token comes at t+1"
        loss = None
        if targets is not None:
            # targets.shape = (batch, seq_len)
            # targets[b, t] = the correct next token after input_ids[b, t]
            # Typically, targets would be input_ids shifted left by one position.
            # Example: 
            # input_ids:  [A, B, C, D]
            # targets:    [B, C, D, <ignore>]
            
            # Flatten for cross-entropy
            loss = F.cross_entropy(
                logits.view(-1, self.vocab_size), # Shape is (batch * seq_len, vocab_size)
                targets.view(-1),              # Shape is (batch * seq_len)
                ignore_index=-1,  # Ignore padding tokens, i.e. ignore position where targets[b,t] == -1
            )
            # What does this do at a HIGH level?
            # It computes the average negative log likelihood of the correct next token
            # according to the model's predicted distribution (logits) over the vocabulary.
            # For each position (b,t), 
            #   First apply softmax to get probabilities over each token in vocab.
            #   Let the correct token for this position be targets[b,t]->y
            #   Then pick the probability assigned to the correct next token y, .i.e prob(y) 
            #   Then take negative log of that probability -log(prob(y))
            # Finally average this value over all (b,t) positions in the batch.

        return logits, loss

    @torch.no_grad()
    def generate(
        self,
        input_ids: torch.Tensor,
        max_new_tokens: int,
        temperature: float = 1.0,
        top_k: Optional[int] = None,
    ) -> torch.Tensor:
        """
        Autoregressive generation

        Args:
            input_ids: Starting tokens (batch, seq_len)
            max_new_tokens: Number of tokens to generate
            temperature: Sampling temperature
            top_k: Top-k sampling (if None, use full distribution)
        Returns:
            Generated sequence (batch, seq_len + max_new_tokens)
        """
        for _ in range(max_new_tokens):
            # Crop context if too long
            # Ensuring the model never attends to more than max_seq_len 
            # tokens during generation.
            input_context = input_ids if input_ids.size(1) <= self.max_seq_len else input_ids[:, -self.max_seq_len:]

            # Forward pass
            logits, _ = self.forward(input_context) # Output of self.forward is (logits, loss)
            # logits.shape = (batch, seq_len, vocab_size)
            # seq_len here is the length of the current context (input_context)
            # logits[b,t,:] gives the probability values for the next token over the 
            # vocabulary after position t.
            logits = logits[:, -1, :] / temperature  # Get last token logits
            # We only care about the probability distribution after the last token
            # for generating the next token.
            # logits.shape after above operation = (batch, vocab_size)

            # Optional top-k sampling
            if top_k is not None:
                values, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < values[:, [-1]]] = -float('Inf')

            # Sample from distribution
            # logits.shape = (batch, vocab_size)
            probs = F.softmax(logits, dim=-1)
            # probs.shape = (batch, vocab_size)
            # probs is a categorical probability distribution over tokens for each batch entry.
            next_token = torch.multinomial(probs, num_samples=1)
            # Sample one token from the distribution for each batch entry
            # next_token.shape = (batch, 1)

            # Append to sequence
            input_ids = torch.cat([input_ids, next_token], dim=1)
            # input_ids.shape = (batch, seq_len + 1)

        return input_ids


def train_epoch(
    model: DecoderOnlyTransformer,
    dataloader: torch.utils.data.DataLoader,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    epoch: int,
) -> float:
    """
    Train for one epoch

    Args:
        model: The transformer model
        dataloader: Training data loader
        optimizer: Optimizer
        device: Device to train on
        epoch: Current epoch number
    Returns:
        Average loss for the epoch
    """
    model.train()
    total_loss = 0.0
    num_batches = 0

    # TODO: Implement training loop
    # For each batch:
    #   1. Move data to device
    #   2. Forward pass (get logits and loss)
    #   3. Backward pass
    #   4. Gradient clipping (max_norm=1.0)
    #   5. Optimizer step
    #   6. Zero gradients
    #   7. Accumulate loss

    # Hint: Use torch.nn.utils.clip_grad_norm_ for gradient clipping
    # Hint: Print progress every 100 batches

    # raise NotImplementedError("TODO: Implement training loop")

    for batch_idx, (states, actions) in enumerate(dataloader):
        #1) Move data to device
        # input_ids = input_ids.to(device)
        # targets = targets.to(device)
        actions = actions.to(device)
        input_ids = actions[:, :-1].contiguous().to(device)  # All tokens except last (batch, seq_len-1)
        targets = actions[:, 1:].contiguous().to(device)     # All tokens except first (batch, seq_len-1)

        #2) Forward pass 
        logits, loss = model(input_ids, targets)
        #3) Backward pass and Zero gradients
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        #4) Gradient clipping
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        #5) Optimizer step
        optimizer.step()
        #6) Accumulate loss
        total_loss += loss.item()
        num_batches += 1

        if batch_idx % 100 == 0:
            print(f"Epoch {epoch+1}, Batch {batch_idx}, Loss: {loss.item():.4f}")

    avg_loss = total_loss / max(num_batches, 1)
    return avg_loss



import os
import pickle
import matplotlib.pyplot as plt
from pathlib import Path
from generate_data import create_dataloaders


def main():
    """
    Main training script

    Usage:
        python backbone.py
    """
    # Hyperparameters
    vocab_size = 256  # Discretized action space
    dim = 256  # Model dimension
    num_layers = 4  # Number of transformer blocks
    num_heads = 8  # Number of attention heads
    ff_hidden_dim = 1024  # Feed-forward hidden dimension
    max_seq_len = 50  # Maximum sequence length
    batch_size = 32
    learning_rate = 1e-4
    num_epochs = 10
    dropout = 0.1

    # Device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # TODO: Load dataset
    # Use the generate_data.py script to create synthetic trajectories
    # Load from data/trajectories.pkl
    data_path = Path("data/trajectories.pkl")
    if not data_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {data_path}. Run `python generate_data.py` first."
        )
    with open(data_path, "rb") as f:
        dataset = pickle.load(f)

    train_loader, val_loader = create_dataloaders(
        dataset,
        batch_size=batch_size,
        train_split=0.9,
    )

    # TODO: Create model
    # model = DecoderOnlyTransformer(...)
    model = DecoderOnlyTransformer(
        vocab_size=vocab_size,
        dim=dim,
        num_layers=num_layers,
        num_heads=num_heads,
        ff_hidden_dim=ff_hidden_dim,
        max_seq_len=max_seq_len,
        dropout=dropout,
    ).to(device)

    # TODO: Create optimizer
    # optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

    # TODO: Training loop
    # for epoch in range(num_epochs):
    #     train_loss = train_epoch(model, train_loader, optimizer, device, epoch)
    #     print(f"Epoch {epoch+1}/{num_epochs} - Loss: {train_loss:.4f}")

    loss_history = []
    for epoch in range(num_epochs):
        train_loss = train_epoch(model, train_loader, optimizer, device, epoch)
        print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {train_loss:.4f}")
        loss_history.append(train_loss)


    # TODO: Save checkpoint
    # torch.save(model.state_dict(), "checkpoints/best_model.pt")
    ckpt_dir = Path("checkpoints/causal_mask_on/")
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = ckpt_dir / "best_model.pt"
    torch.save(model.state_dict(), ckpt_path)
    print(f"Training complete. Checkpoint saved to {ckpt_dir / 'best_model.pt'}")


    # Plot training loss
    img_dir = Path("images/causal_mask_on/")
    img_dir.mkdir(parents=True, exist_ok=True)

    plt.figure()
    plt.plot(range(1, num_epochs + 1), loss_history, marker="o")
    plt.title("Training Loss over Epochs")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.savefig(img_dir / "training_loss.png", dpi=200, bbox_inches="tight")
    plt.close()
    print(f"Saved loss curve to {img_dir / 'training_loss.png'}")



if __name__ == "__main__":
    main()
